# -*- coding: utf-8 -*-
"""Код.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12L5qhqfB29xuZe8z0GIVRFL6vw0zyEX1
"""

import warnings
import numpy as np
import scipy.sparse as sp
from scipy.sparse.linalg import (
    cg, gmres, bicgstab, spilu, LinearOperator, eigsh
)
from scipy.linalg import cho_factor, cho_solve
from scipy.sparse.csgraph import connected_components
from typing import Optional, Tuple, Dict, Any

try:
    from mpi4py import MPI
    MPI_AVAILABLE = True
except ImportError:
    MPI_AVAILABLE = False

try:
    import petsc4py
    petsc4py.init([])
    from petsc4py import PETSc
    PETSC_AVAILABLE = True
except ImportError:
    PETSC_AVAILABLE = False
try:
    import cupy as cp
    import cupyx.scipy.sparse.linalg as cpsl
    from cupyx.scipy.sparse import csr_matrix as cp_csr
    GPU_AVAILABLE = True
except ImportError:
    GPU_AVAILABLE = False
class MatrixAnalyzer:
    @staticmethod
    def analyze(A: sp.spmatrix | np.ndarray) -> Dict[str, Any]:
        if sp.issparse(A):
            A = A.tocsr()
        else:
            A = np.asarray(A)

        info = {
            'shape': A.shape,
            'is_sparse': sp.issparse(A),
            'symmetric': False,
            'positive_definite': False,
            'block_diagonal': False,
        }
        if sp.issparse(A):
            diff = (A - A.T).data
            info['symmetric'] = np.allclose(diff, 0, atol=1e-12)
        else:
            info['symmetric'] = np.allclose(A, A.T, atol=1e-12)
        if info['symmetric']:
            try:
                if sp.issparse(A):
                    val = eigsh(A, k=1, which='SA', return_eigenvectors=False,
                                maxiter=1000, tol=1e-6)[0]
                    info['positive_definite'] = val > 1e-10
                else:
                    if A.shape[0] <= 2000:
                        try:
                            cho_factor(A)
                            info['positive_definite'] = True
                        except np.linalg.LinAlgError:
                            info['positive_definite'] = False
                    else:
                        info['positive_definite'] = False
            except Exception:
                info['positive_definite'] = False
        info['block_diagonal'] = MatrixAnalyzer._detect_block_diagonal(A)
        return info
    @staticmethod
    def _detect_block_diagonal(A) -> bool:
        if not sp.issparse(A):
            return False
        n = A.shape[0]
        if n <= 2:
            return False
        Asp = A.tocoo()
        edges = np.vstack([Asp.row, Asp.col])
        graph = sp.csr_matrix((np.ones(len(edges[0])), edges), shape=(n, n))
        n_comp, labels = connected_components(graph, directed=False)
        if n_comp <= 1:
            return False
        sizes = np.bincount(labels)
        return np.any(sizes > 1)

    @staticmethod
    def environment() -> Dict[str, bool]:
        return {
            'mpi': MPI_AVAILABLE,
            'gpu': GPU_AVAILABLE,
            'petsc': PETSC_AVAILABLE,
        }
class SolverSelector:
    RULES = {
        'spd':             ('CG', 'IC'),
        'symmetric_indef': ('GMRES(200)', 'ILU'),
        'general':         ('BiCGSTAB', 'ILUT'),
        'block':           ('GMRES(200)', 'block'),
    }

    @staticmethod
    def select(info: Dict[str, Any]) -> Tuple[str, str]:
        if info['block_diagonal']:
            return SolverSelector.RULES['block']
        if info['symmetric']:
            if info['positive_definite']:
                return SolverSelector.RULES['spd']
            else:
                return SolverSelector.RULES['symmetric_indef']
        return SolverSelector.RULES['general']
class ParallelSolver:
    @staticmethod
    def _build_preconditioner(A, precond_name: str) -> LinearOperator:
        n = A.shape[0]
        if precond_name == 'IC':
            try:
                lu = spilu(A.tocsc(), drop_tol=1e-4)
            except RuntimeError:
                lu = spilu(A.tocsc(), drop_tol=1e-2)
            return LinearOperator((n, n), matvec=lambda x: lu.solve(x))
        elif precond_name == 'ILU':
            lu = spilu(A.tocsc(), drop_tol=1e-4, fill_factor=10)
            return LinearOperator((n, n), matvec=lambda x: lu.solve(x))
        elif precond_name == 'ILUT':
            lu = spilu(A.tocsc(), drop_tol=1e-4, fill_factor=20)
            return LinearOperator((n, n), matvec=lambda x: lu.solve(x))
        elif precond_name == 'block':
            return ParallelSolver._block_diag_preconditioner(A)
        else:
            return LinearOperator((n, n), matvec=lambda x: x, rmatvec=lambda x: x)
    @staticmethod
    def _block_diag_preconditioner(A: sp.spmatrix) -> LinearOperator:
        n = A.shape[0]
        Asp = A.tocoo()
        edges = np.vstack([Asp.row, Asp.col])
        graph = sp.csr_matrix((np.ones(len(edges[0])), edges), shape=(n, n))
        n_comp, labels = connected_components(graph, directed=False)

        blocks_lu = []
        for comp_id in range(n_comp):
            idx = np.where(labels == comp_id)[0]
            block = A[np.ix_(idx, idx)].toarray()
            try:
                if np.allclose(block, block.T):
                    lu = cho_factor(block)
                else:
                    lu = np.linalg.lu_factor(block)
            except np.linalg.LinAlgError:
                lu = np.linalg.lu_factor(block + 1e-12*np.eye(len(block)))
            blocks_lu.append((idx, lu))
        def matvec(x):
            y = np.zeros_like(x)
            for idx, lu in blocks_lu:
                xi = x[idx]
                if isinstance(lu, tuple) and len(lu) == 2:  # LU
                    yi = np.linalg.lu_solve(lu, xi)
                else:
                    yi = cho_solve(lu, xi)
                y[idx] = yi
            return y
        return LinearOperator((n, n), matvec=matvec, rmatvec=matvec)
    @staticmethod
    def _solve_gpu(A, b, method: str) -> np.ndarray:
        if sp.issparse(A):
            A_gpu = cp_csr(A)
        else:
            A_gpu = cp.asarray(A)
        b_gpu = cp.asarray(b)
        if method == 'CG':
            x_gpu, info = cpsl.cg(A_gpu, b_gpu)
        elif method == 'BiCGSTAB':
            x_gpu, info = cpsl.bicgstab(A_gpu, b_gpu)
        elif method.startswith('GMRES'):
            restart = int(method.split('(')[1].strip(')'))
            x_gpu, info = cpsl.gmres(A_gpu, b_gpu, restart=restart)
        if info != 0:
            warnings.warn(f"GPU solver exited with info={info}")
        return cp.asnumpy(x_gpu)

    @staticmethod
    def _solve_mpi_petsc(A, b, method: str) -> np.ndarray:
        comm = MPI.COMM_WORLD
        rank = comm.Get_rank()
        size = comm.Get_size()
        n = A.shape[0]
        rows_per_proc = [n // size + (1 if i < n % size else 0) for i in range(size)]
        start_row = sum(rows_per_proc[:rank])
        local_n = rows_per_proc[rank]
        A_petsc = PETSc.Mat().create(comm)
        A_petsc.setSizes([local_n, n])
        A_petsc.setType('aij')
        A_petsc.setUp()
        if sp.issparse(A):
            A_csr = A.tocsr()
        else:
            A_csr = sp.csr_matrix(A)
        for i in range(local_n):
            global_row = start_row + i
            row_data = A_csr.getrow(global_row)
            cols = row_data.indices
            vals = row_data.data
            A_petsc.setValues([global_row], cols, vals, addv=False)
        A_petsc.assemblyBegin()
        A_petsc.assemblyEnd()
        b_petsc = PETSc.Vec().createMPI(comm, local_n, n)
        x_petsc = PETSc.Vec().createMPI(comm, local_n, n)
        b_local = b[start_row:start_row+local_n]
        b_petsc.setValues(range(local_n), b_local, addv=False)
        b_petsc.assemblyBegin()
        b_petsc.assemblyEnd()
        ksp = PETSc.KSP().create(comm)
        ksp.setOperators(A_petsc)
        if method == 'CG':
            ksp.setType('cg')
        elif method == 'BiCGSTAB':
            ksp.setType('bcgs')
        elif method.startswith('GMRES'):
            restart = int(method.split('(')[1].strip(')'))
            ksp.setType('gmres')
            ksp.setGMRESRestart(restart)
        else:
            ksp.setType('gmres')
        ksp.pc.setType('jacobi')
        ksp.setTolerances(rtol=1e-10, atol=1e-12, max_it=1000)
        ksp.solve(b_petsc, x_petsc)
        solution = np.zeros(n)
        x_local = x_petsc.getArray()
        solution[start_row:start_row+local_n] = x_local
        all_sizes = comm.allgather(local_n)
        offsets = [sum(all_sizes[:i]) for i in range(size)]
        recvbuf = np.zeros(n) if rank == 0 else None
        comm.Gatherv(x_local, [recvbuf, all_sizes, offsets, MPI.DOUBLE], root=0)
        if rank == 0:
            return recvbuf
        else:
            return None
    @staticmethod
    def solve(A, b, method: str, precond_name: str,
              use_gpu: bool = False, use_mpi: bool = False) -> np.ndarray:
        if use_mpi and MPI_AVAILABLE and PETSC_AVAILABLE:
            comm = MPI.COMM_WORLD
            rank = comm.Get_rank()
            x_global = ParallelSolver._solve_mpi_petsc(A, b, method)
            if rank == 0:
                return x_global
            else:
                return None
        if use_gpu and GPU_AVAILABLE:
            try:
                return ParallelSolver._solve_gpu(A, b, method)
            except Exception as e:
                warnings.warn(f"GPU решение не удалось: {e}, переключаюсь на CPU")
        M = ParallelSolver._build_preconditioner(A, precond_name)
        if method == 'CG':
            x, info = cg(A, b, M=M)
        elif method == 'BiCGSTAB':
            x, info = bicgstab(A, b, M=M)
        elif method.startswith('GMRES'):
            restart = int(method.split('(')[1].strip(')'))
            x, info = gmres(A, b, M=M, restart=restart)
        else:
            raise ValueError(f"Неизвестный метод {method}")
        if info != 0:
            warnings.warn(f"Решатель {method} завершился с кодом {info}")
        return x

class Postprocessor:
    @staticmethod
    def residual(A, x, b) -> float:
        b_norm = np.linalg.norm(b)
        if b_norm == 0:
            return np.linalg.norm(A @ x - b)
        return np.linalg.norm(A @ x - b) / b_norm

    @staticmethod
    def error(x, x_ref) -> Optional[float]:
        if x_ref is None:
            return None
        ref_norm = np.linalg.norm(x_ref)
        if ref_norm == 0:
            return np.linalg.norm(x - x_ref)
        return np.linalg.norm(x - x_ref) / ref_norm

def solve_system(A, b, x_ref=None,
                 force_mpi=False, force_gpu=False):
    info = MatrixAnalyzer.analyze(A)
    env = MatrixAnalyzer.environment()
    method, precond = SolverSelector.select(info)
    use_mpi = force_mpi and env['mpi'] and env['petsc']
    use_gpu = force_gpu and env['gpu']
    x = ParallelSolver.solve(A, b, method, precond, use_gpu=use_gpu, use_mpi=use_mpi)
    if use_mpi:
        comm = MPI.COMM_WORLD
        rank = comm.Get_rank()
        if rank != 0:
            return None, {}

    res = Postprocessor.residual(A, x, b)
    err = Postprocessor.error(x, x_ref)

    meta = {
        'method': method,
        'preconditioner': precond,
        'residual': res,
        'error': err,
        'symmetric': info['symmetric'],
        'positive_definite': info['positive_definite'],
        'block_diagonal': info['block_diagonal'],
        'mpi_used': use_mpi,
        'gpu_used': use_gpu,
    }
    return x, meta

if __name__ == '__main__':

    print("Метод:", meta['method'])
    print("Предобусловливатель:", meta['preconditioner'])
    print("Относительная невязка:", meta['residual'])
    print("Относительная ошибка:", meta['error'])